language: node_js
cache: 
  directories: 
    - node_modules
    - ~/.npm
deploy: 
  commit_message: "Deploy Release"
  edge: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/
  provider: pages
  skip_cleanup: true
  target-branch: gh-pages
  true: ~
node_js: 
  - "14"
script: 
  - "yarn build"
